### PR TITLE
Fix typos and update HIPE references

### PR DESCRIPTION
**Pull request by TimoGlastra**
I'm reading all RFCs at the moment. While reading I noticed some typos and old references to HIPEs that now have Aries RFCS. I'm now updating them while reading. Not done yet. More of a general question if this is appreciated? If so, I will continue.

### CODE REVIEW

**Comment by TelegramSam** [comment]
This is very helpful, thank you! As soon as you change the status from draft, I'll check and merge.

**Comment by dhh1128** [comment]
+1 on this. Thank very much, @TimoGlastra . We'll be happy to merge.

**Comment by dhh1128** [comment]
@TimoGlastra : I wanted to say that I've reviewed the changes accumulated so far, and they are great! We can merge changes as soon as you like -- even if you want to raise additional changes later.

**Comment by TimoGlastra** [comment]
Glad the changes are helpful. You could merge the current changes in this PR and I will create additional PRs while I continue reading. This would avoid one gigantic PR. For me it makes no difference if it will be one or multiple PRs. So please let me know how you prefer to proceed

**Comment by dhh1128** [comment]
I would like to merge in a granular way. Let's get this merged and then do additional updates as you go.

**Pull request merged**
