### PR TITLE
0289 ToIP-stack - Introduce Verification of Authoritative Verifiers

### PR DESCRIPTION
**Pull request by Oskar-van-Deventer**
Introduce Verification of Authoritative Verifiers
Signed-off-by: Oskar van Deventer <46109652+oskar-van-deventer@users.noreply.github.com>

### CODE REVIEW

**Comment by Oskar-van-Deventer** [comment]
Can somebody tell me how I deal with this annoying DCO stuff? The "help" refers to command line command, but I am doing all the editing in the browser. What is the place where I can simply enter my github password, and DCO accepts my signature?

**Comment by swcurran** [comment]
When you commit your change, make sure that this is in the commit message:

```
This is my commit message

Signed-off-by: Random J Developer <random@developer.example.org>
```

The name and email address must match your github account.

Clicking the details on the "DCO Action Required" may give you a way to correct this. Or, close this one and do it again -- should be a cut'n'paste.

**Comment by Oskar-van-Deventer** [comment]
> When you commit your change, make sure that this is in the commit message:
> 
> ```
> This is my commit message
> 
> Signed-off-by: Random J Developer <random@developer.example.org>
> ```
> 
> The name and email address must match your github account.
> 
> Clicking the details on the "DCO Action Required" may give you a way to correct this. Or, close this one and do it again -- should be a cut'n'paste.

**Comment by Oskar-van-Deventer** [comment]
Going to try the DCO stuff again ...

**Pull request closed without merging**
