### PR TITLE
feat: add push notifications expo protocol

### PR DESCRIPTION
**Pull request by TimoGlastra**
Adds push notification expo protocol to be used with [Expo's push notification service](https://docs.expo.dev/push-notifications/overview/)

Similar to #736 and #699

### CODE REVIEW

**Review by blu3beri — APPROVED** [review]
LGTM!

**Comment by TimoGlastra** [comment]
This should also be updated to incorporate changes as discussed in #736

**Comment by TelegramSam** [comment]
Is this ready to merge given the change in #736?

**Comment by swcurran** [comment]
Reviewing PRs. I need some experts in mobile development to review and weigh in on this.

@TimoGlastra @blu3beri — could you of you please remove the other two files from this PR?  The index.md file should will be a follow up to the merging we are doing with other PRs, and the fix in the other PR should be done in a separate (trivial) PR.

Thanks!

**Comment by TelegramSam** [comment]
Discussed 20241009 - Want to merge, but need the conflicts handled.

**Review by dbluhm — APPROVED** [review]

**Pull request merged**
