### PR TITLE
added more actual words to acronyms in this document

### PR DESCRIPTION
**Pull request by Identitywoman**

### CODE REVIEW

**Comment by swcurran** [comment]
Hi @Identitywoman - thanks for the contributions.  Unfortunately, there is a IP issue with the contributions that must be fixed before we can merge them.  Hyperledger commits must have a Developer Certificate of Origin (DCO).

Not sure what git tool you are using, but the "-s" option needs to be on commits.  There are some instructions in the Contributions file in the repo that gives guidance on how to amend the commits you have done to add DCO - https://github.com/hyperledger/aries-rfcs/blob/e6c96a872bbdc9b111afb64120ec88b59a4991c2/contributing.md#signing-off-commits-dco See the section about that one for more about DCO.

Can you please follow those steps so we can merge these changes?

**Comment by kdenhartog** [comment]
I just found this to show how DCO can be handled in the web app. https://community.openhab.org/t/dco-check-signing-off-with-github-web-editor-explanation/83330

See the section about "in the GitHub editor" in the first post.

**Comment by dhh1128** [comment]
@Identitywoman : I can fix this the same way I [offered to tweak the other commit](https://github.com/hyperledger/aries-rfcs/pull/272#issuecomment-549461887), if you approve.

**Comment by Identitywoman** [comment]
I actually have almost no clue on what button to push and into what field on the next screen to write what I need to write to get you to accept the changes. I tried...as you can see...I'm happy to follow a bouncing ball but I am not sure where ... BTW I'm just editing via the web interface.

**Comment by dhh1128** [comment]
PR #300 is a cherry-pick of @Identitywoman 's commit from this PR (`703c30d`), minus all the cruft that was bogging this down. I modified the commit message to include Kaliya's DCO signoff as listed in the comment stream above, except that I had to use the same email address that is used for the author's identity (the one in the github account).

Since PR 300 has been merged, this PR is now redundant and can be closed.

**Pull request closed without merging**
