### PR TITLE
pluralize lists, call preview a preview

### PR DESCRIPTION
**Pull request by sklump**
Signed-off-by: sklump <srklump@hotmail.com>
... also tweak json listings to avoid red blotches on display

### CODE REVIEW

**Comment by sklump** [comment]
Also, note that the preview is called a preview in the credential offer - it should be called a preview in the proposal

**Comment by swcurran** [comment]
This looks good to me.  @llorllale does the Aries Framework Go team have any concerns with the tweaks here?  They seem correct.

Has anyone else already implemented this protocol?

**Comment by sklump** [comment]
Also: in credential request, should there be text about the replacement id must match any received in the offer, if in response to an offer with a replacement id? Otherwise, the holder must know an issuer-unique identifier, which is awkward.

**Comment by sklump** [comment]
OK, good to go I believe

**Comment by swcurran** [comment]
@llorllale can you please review and approve if OK?  Note that since the Wednesday meeting another field was dropped -- "replacement_id" in the "credential request" message.  It should not be there is probably a cut'n'paste typo from somewhere.

**Review by llorllale — APPROVED** [review]

**Review by swcurran — APPROVED** [review]
LGTM

**Pull request merged**
