### PR TITLE
RFC 418: Rich Schema Encoding Objects

### PR DESCRIPTION
**Pull request by brentzundel**
Describes Rich Schema encoding objects and how they may be implemented within Aries.

Signed-off-by: Brent <brent.zundel@gmail.com>

### CODE REVIEW

**Comment by brentzundel** [comment]
@swcurran @dhh1128 can you help me understand what to expect when proposing a new RFC?

This PR has been waiting for 10 days now, has passed the circleci tests, and hasn't had any requests from maintainers for process changes. What is the next step?

**Comment by dhh1128** [comment]
The main thing that you need to do is get someone's attention. I get notifications when I'm mentioned, but not when a PR is raised. :-)

**Comment by swcurran** [comment]
@brentzundel - there is also a label called "Merge Ready" that lets us know that it's ready to go. If we see that, we're not going to hold up a merge.

We'll remind folks of that over the next little bit.  Also make sure that's referenced in the contributors guide.

**Comment by brentzundel** [comment]
Thanks folks.

**Pull request merged**
