### PR TITLE
Rfc 454 tweaks

### PR DESCRIPTION
**Pull request by sklump**

### CODE REVIEW

**Review by swcurran — APPROVED** [review]
LGTM - thanks. @TelegramSam -- could you please merge?

**Review by llorllale — DISMISSED** [review]
Let's also fix `proposal~attach` while we are at it.

**Comment by llorllale** [comment]
Hi @sklump 

Can you please pluralize `proposal~attach`? This PR looks good otherwise.

**Comment by dhh1128** [comment]
approved on community B call on 24 Mar 2021; suggestion by @llorllale was included

**Pull request merged**
