### PR TITLE
add goal code to didx request

### PR DESCRIPTION
**Pull request by domwoe**
In response to #671 
I'm not confident to provide a [Message Catalogue Section](https://github.com/hyperledger/aries-rfcs/blob/master/features/0434-outofband/README.md#goal_code) as of now.

Signed-off-by: Woerner Dominic (RBCH/PJ-IOT) <dominic.woerner2@ch.bosch.com>

### CODE REVIEW

**Comment by swcurran** [comment]
@TelegramSam @dhh1128 @troyronda @andrewwhitehead @llorllale 

I think this is useful and should be added before we lock in AIP 2.0.  It adds optional fields, so it technically a minor update, although I think there can be flexibility on that given we are before locking in AIP 2.0.

What do you think?   

The only issue for me is what @domwoe mentioned above about not providing a Message Catalogue section as we don't really know what this will be used for -- just that it should be available.

Please respond earlier than later.

**Comment by andrewwhitehead** [comment]
There's a couple typos around the word 'particular', but I think it's a good addition.

**Comment by dhh1128** [comment]
+1 from me

**Review by dhh1128 — APPROVED** [review]
LGTM

**Review by TelegramSam — APPROVED** [review]

**Pull request merged**
