### PR TITLE
simplify please ack decorator

### PR DESCRIPTION
**Pull request by TimoGlastra**
Simplify please ack decorator for inclusion in AIP 2.0 (#632). I simplified it to the most basic version where you can only indicate whether you want an ack on RECEIPT or OUTCOME. 

I'm not sure if I removed too much, but I think this basic variant will be quite easy to implement for agents, while still providing a lot of value.

@dhh1128 as the original author of the RFC, what do you think?

### CODE REVIEW

**Review by swcurran — APPROVED** [review]
LGTM

**Comment by TimoGlastra** [comment]
From WG call:

- Make `on` an array
- Describe generic behaviour for `OUTCOME`
	- when interaction is done / outcome reached -> ack sent
	- Allow protocols to overwrite `OUTCOME` behaviour

**Review by dhh1128 — APPROVED** [review]
I am okay with the simplifications in this PR. I am happy that we retained a reference to the earlier version of the RFC so the advanced features can still be discovered for possible exploration in a future RFC. Thanks.

**Review by swcurran — CHANGES_REQUESTED** [review]
Preventing merge until array update made.

**Review by swcurran — APPROVED** [review]

**Pull request merged**
