### PR TITLE
Rename bcgov/indy-catalyst to hyperledger/aries-vcr

### PR DESCRIPTION
**Pull request by WadeBarnes**
- indy-catalyst is being renamed to aries-vcr and being contributed to Hyperledger
- https://github.com/bcgov/aries-vcr/issues/464

Signed-off-by: Wade Barnes <wade.barnes@shaw.ca>

### CODE REVIEW

**Comment by WadeBarnes** [comment]
Staging these changes for when the transfer is complete.

**Comment by dhh1128** [comment]
@WadeBarnes : What would you like to do about this PR? I am trying not to let it languish without attention...

**Comment by WadeBarnes** [comment]
@swcurran, do we want to close this for now and re-open it when we're closer to actually transferring the aries-vcr repo?

**Comment by swcurran** [comment]
Yup - let's close it.

**Pull request closed without merging**
