### PR TITLE
Update the RFC to transition to Step 2. Does not include update ALL RFCs to change from did:sov...

### PR DESCRIPTION
**Pull request by swcurran**

### CODE REVIEW

**Comment by swcurran** [comment]
This step SHOULD include changing (almost) all references from "did:sov..." to "https://didcomm.org/".  Almost, because at least this RFC has some references that need to stay the same.

**Comment by swcurran** [comment]
Should all of the other RFCs be updated in this PR or a follow up?

**Review by dhh1128 — APPROVED** [review]
Looks fine.

**Comment by dhh1128** [comment]
Vote taken on community call on 23 Sep 2020: agreed to merge.

**Pull request merged**
