### PR TITLE
RFC0334: add curve P-384

### PR DESCRIPTION
**Pull request by llorllale**
Signed-off-by: George Aristy <george.aristy@securekey.com>

### CODE REVIEW

**Review by Baha-sk — APPROVED** [review]
I'm currently adding concrete examples into this rfc

**Review by kdenhartog — APPROVED** [review]

**Comment by dhh1128** [comment]
I'm not opposed to this simple and desirable update, on principle. However, I remember a discussion about which curves and algorithms needed support in DIDComm v2, and I remember a subtlety about curve 384 versus some other values. Can we make sure we're aligned with whatever DIDComm v2 is going to require? @kdenhartog and @TelegramSam may remember that discussion in the DIDComm WG at DIF...

**Comment by kdenhartog** [comment]
> I'm not opposed to this simple and desirable update, on principle. However, I remember a discussion about which curves and algorithms needed support in DIDComm v2, and I remember a subtlety about curve 384 versus some other values. Can we make sure we're aligned with whatever DIDComm v2 is going to require? @kdenhartog and @TelegramSam may remember that discussion in the DIDComm WG at DIF...

I'm not remembering the subtlety off the top of my head, but I'll look back through the issues to see if I can jog my memory. Looking at the registries in DIDCommV2 we are getting closer with this addition as well: https://identity.foundation/didcomm-messaging/spec/#key-wrapping-algorithms. When I go through the DIDComm spec to remove the anoncrypt stuff I'll make sure everything is lined up as well.

**Comment by llorllale** [comment]
Hearing no objections, I'm merging this simple change that does not change the RFC's status.

**Pull request merged**
