### PR TITLE
Revisit presentation preview

### PR DESCRIPTION
**Pull request by sklump**
to allow for unrevealed attrs and self-attested attrs; remove non-revocation timestamps from presentation preview.

### CODE REVIEW

**Comment by sklump** [comment]
Hello,

I think I should get my protoype's unit tests to pass first. I hope I can say OK in about 24 hours (16:00 EDT), but golf off for the moment thanks.

Cheers
Stephen

Sent from my HTC

----- Reply message -----

**Comment by kdenhartog** [comment]
Sounds good 👍

**Comment by dhh1128** [comment]
I think these are good changes and should be merged. Just noting that whichever PR is merged first (this one or #189 ), the other will have some merge conflicts that need to be resolved.

**Comment by sklump** [comment]
Hello, I've got all my unit tests to pass on my prototype. I believe you should merge this as is and then we can revisit what to take out and/or add from this position of strength.

**Comment by sklump** [comment]
I will rework #0036 and #0037 with Daniel's implicit attribute specification encoding in their respective preview inner message objects, then submit another PR.

**Pull request closed without merging**
