### PR TITLE
Proposed LegacyPeer DID Method

### PR DESCRIPTION
**Pull request by TelegramSam**

### CODE REVIEW

**Comment by TelegramSam** [comment]
Related to #735

**Comment by TelegramSam** [comment]
Needs a hint about where you are likely to encounter them: existing wallets and codebases.
IndySDK wallets, ACA-Py, AFJ, Bifold, Askar

Effects on Mediation Coordination

**Comment by TelegramSam** [comment]
Paused per discussion in WG. Expecting to bypass this method with a translation to another method directly.

**Comment by swcurran** [comment]
Discussed on the Aries Working Group call on 2023.06.28 and there was agreement that this should be closed (not merged) as we have agreed instead to migrate unqualified DIDs to did:peer:3.

@TelegramSam -- sorry you missed the meeting. Please reopen if you would like this discussed further.

**Pull request closed without merging**
