### PR TITLE
Fix anoncrypt notation mistake

### PR DESCRIPTION
**Pull request by Patrik-Stas**

### CODE REVIEW

**Comment by swcurran** [comment]
@Patrik-Stas - thanks for the update. Unfortunately, your commit was not signed for DCO purposes and so cannot be merged.  Please take a look at the Contributors guidelines about DCO:

https://github.com/hyperledger/aries-rfcs/blob/master/contributing.md#signing-off-commits-dco

**Comment by Patrik-Stas** [comment]
@swcurran thanks for heads up, fixed now

**Comment by swcurran** [comment]
Thanks.  I'm not clear enough on the example to be certain if the proposed change is appropriate, so will leave it to @dhh1128 to review this one. Is the example intended to be inter- or intra-domain?

**Comment by Patrik-Stas** [comment]
To clarify requested change, it seems that `~` is for expressing intra-domain relationship. But based on text surrounding the proposed modifications, anoncryption `/` was supposed to be expressed. Hence the changes, but if I missing something, I'll be glad to learn :-)

**Pull request merged**
