### PR TITLE
clarify URL shortening

### PR DESCRIPTION
**Pull request by b1conrad**
Signed-off-by: Bruce Conrad <bruce_conrad@byu.edu>

This change loosens the requirements for URL shortening to reflect actual usage.

1. The GUID used to track out-of-band messages may be embedded in the short URL path, rather than as a query string `id` parameter value.
2. The sender may respond to the short URL by redirecting to the long URL.

### CODE REVIEW

**Review by swcurran — COMMENTED** [review]
Looks great to me -- much appreciated!  I wrote the original and really did not know the best practices in this area. 

I won't mark this as approved until those with more knowledge in this area review it -- e.g. @TelegramSam @dhh1128

**Review by dhh1128 — COMMENTED** [review]
I am generally okay with this. However, I want to be sure we can recognize the GUID of the OOB message when it appears as something other than the value of an `id` parameter. Are we sure that is the case? (I don't believe message IDs are required to be GUIDs -- only recommended to be something unique -- so I don't believe we can detect which segment of a path is a message ID just by looking for something that matches a GUID regex.)

**Review by swcurran — APPROVED** [review]
Discussed on Aries WG Call 2021.04.28

**Comment by swcurran** [comment]
@b1conrad -- can you please update the branch?  We can't merge until that's done.  Thanks!

**Comment by TelegramSam** [comment]
> I am generally okay with this. However, I want to be sure we can recognize the GUID of the OOB message when it appears as something other than the value of an `id` parameter. Are we sure that is the case? (I don't believe message IDs are required to be GUIDs -- only recommended to be something unique -- so I don't believe we can detect which segment of a path is a message ID just by looking for something that matches a GUID regex.)

The `id` here is not the message ID, just a unique id for message retrieval. In this case, I'm not even sure we need to recognize the attribute, or that it needs to be a GUID.  Or am I missing something?

**Comment by dhh1128** [comment]
Okay, I see now how this id is opaque. Concern withdrawn. Full speed ahead.

**Pull request merged**
