### PR TITLE
fix: RFC0434 - pluralize fields as per RFC0074

### PR DESCRIPTION
**Pull request by llorllale**
Pluralized fields as per the best practice documented in [RFC0074](https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0074-didcomm-best-practices/README.md#pluralization).

Signed-off-by: George Aristy <george.aristy@securekey.com>

### CODE REVIEW

**Comment by llorllale** [comment]
Appreciate a double-check - it was sometimes difficult to discern `service` in the context of a DID document vs an OOB message.

**Comment by swcurran** [comment]
Heads up @shaangill025.  We'll want this in OOB asap when merged.

**Review by swcurran — CHANGES_REQUESTED** [review]
Maybe add line 236 to the changes (I couldn't add a comment there). I think it references `services` in the message.  I didn't see any other instances.

**Comment by llorllale** [comment]
@swcurran 

> Maybe add line 236 to the changes (I couldn't add a comment there). I think it references services in the message. I didn't see any other instances.

Done.

**Review by swcurran — APPROVED** [review]

**Pull request merged**
