### PR TITLE
RFC 0771: 'cred' to 'credential' in identifiers

### PR DESCRIPTION
**Pull request by genaris**
Fix a few typos in identifiers (cred-filter -> credential-filter and cred-request -> credential-request) to be consistent with the rest of the document.

### CODE REVIEW

**Review by TimoGlastra — APPROVED** [review]

**Comment by TelegramSam** [comment]
Does this change match the historical, currently in-use reality?

**Comment by genaris** [comment]
> Does this change match the historical, currently in-use reality?

AFAIK this is not yet used in production, and the first and currently only implementation is the one for AFJ (where I noticed this inconsistency). That one of course matches this change.

**Review by swcurran — APPROVED** [review]

**Comment by swcurran** [comment]
@genaris Please update the branch so we can merge this.  Thanks!

**Comment by genaris** [comment]
> @genaris Please update the branch so we can merge this. Thanks!

Done!

**Pull request merged**
