### PR TITLE
Add ECDH-ES for Anoncrypt in Envelope v2

### PR DESCRIPTION
**Pull request by troyronda**
Signed-off-by: Troy Ronda <troy@troyronda.com>

### CODE REVIEW

**Review by Baha-sk — APPROVED** [review]

**Comment by andrewwhitehead** [comment]
LGTM

**Review by andrewwhitehead — APPROVED** [review]

**Comment by troyronda** [comment]
Related: https://github.com/decentralized-identity/didcomm-messaging/pull/190

**Comment by swcurran** [comment]
I'm pretty much a newbie on this trying to understand the ramifications, so my opinion counts for very little. I lean to what @dhh1128 has been saying and that we should stick to only using ECDH-1PU (authcrypt) for DIDComm. Both sides of the messaging should know with whom they are interacting.

**Review by llorllale — APPROVED** [review]

**Comment by llorllale** [comment]
Anoncrypt particularly shines in routing use cases.

**Comment by dhh1128** [comment]
I don't have serious heartburn about supporting ECDH-ES in DIDComm. My concerns were about implementing the Presentation Exchange protocol in anoncrypt mode rather than the existence of anonycrypt in general.

Of course, if we leave ECDH-ES out of DIDComm, we can prevent PEx from making what I consider a mistake...

**Comment by swcurran** [comment]
Should there be guidance on when to use authcrypt vs. anoncrypt?  For example, authcrypt must be used for messages between sender and recipient, while anoncrypt may be used for messages to and from mediators and relays?

**Comment by troyronda** [comment]
@swcurran I think guidance is helpful.

How's this:

> DIDComm defines both the concept of authenticated sender encryption (aka `Authcrypt`) and anonymous sender encryption (aka `Anoncrypt`).
In general, Aries RFCs and protocols use `Authcrypt` to exchange messages.
In some limited scenarios (e.g., mediator and relays), an Aries RFC or protocol may define usage of `Anoncrypt`.

**Comment by swcurran** [comment]
I'd be happy with that.

**Comment by troyronda** [comment]
@swcurran added the guidance text: https://github.com/hyperledger/aries-rfcs/compare/f39c12fb0b7dc43b2fa283718b9140c033bad44f..02c6b4efc6169ebd5e91dbd2085a8bef3c4bc031

**Review by swcurran — APPROVED** [review]

**Comment by swcurran** [comment]
Sounds like we've arrived at a happy place.  I'll wait a bit more in case someone else wants to weigh in on the last changes and then will merge this.  Speak now...  :-)

**Pull request merged**
