### PR TITLE
RFC 0011: Decorators --> ACCEPTED; Deadline 2019.12.06

### PR DESCRIPTION
**Pull request by dhh1128**
Signed-off-by: Daniel Hardman <daniel.hardman@gmail.com>

### CODE REVIEW

**Comment by tplooker** [comment]
I think this PR covers the topic well, as a related note do we have thoughts on how decorators will be expressed under the discovery protocol?

**Comment by dhh1128** [comment]
Update: this PR is on hold pending a resolution to issue #78 ; there was a late-breaking comment there that is relevant to what's proposed here.

**Comment by swcurran** [comment]
Per discussions in #79 that has now been closed, this status change has been re-activated, with a new 2 week deadline for discussion.

**Comment by swcurran** [comment]
Final call. Any objections to this PR/Status Change from being merged?

@dhh1128 @tplooker @TelegramSam

**Comment by dhh1128** [comment]
Nope. I say merge it.

**Comment by swcurran** [comment]
@dhh1128 - can you push a commit to the index.md file to get it up to date?  I'm not sure how to do that...

Thanks

**Comment by dhh1128** [comment]
On it. ETA 15 min.

**Pull request merged**
