### PR TITLE
Update RFC 0023 DID exchange msg type

### PR DESCRIPTION
**Pull request by troyronda**
Updates message @type prefix to https://didcomm.org

Signed-off-by: Troy Ronda <troy@troyronda.com>

### CODE REVIEW

**Comment by troyronda** [comment]
@kdenhartog I didn’t see DID exchange in the test suite.

**Comment by llorllale** [comment]
Yeah - the test suite does not test the did-exchange protocol.

**Comment by dhh1128** [comment]
@kdenhartog Since there are not currently any dependencies we could break, I say go ahead and merge.

**Comment by kdenhartog** [comment]
Sounds good thanks for checking. I see there's an issue filed on the test suite to add that. It should conform to this going forward. I'll go ahead and merge this update.

**Pull request merged**
